### PR TITLE
Pull Request for 3.5.0

### PR DESCRIPTION
**Pull request by Rsl1122**

### CODE REVIEW

**Comment by mibby** [comment]
@Rsl1122 Any chances on getting a dev build of the v3.5 branch as of commit https://github.com/Rsl1122/Plan-PlayerAnalytics/commit/b0045077f6ced063d4e3bf8def45626db6b212d5 for testing? Manually compiling fails due to missing dependencies and the pom repositories don't seem to point to anything that includes the dependencies. 

Compiling Plan fails due to missing BukkitPluginDependency 1.1.0 and PlanPluginBridge 3.5.0.
Compiling PlanPluginBridge fails due to missing Plan 3.5.0 and a bunch of the various compatibility dependencies. :P

**Comment by Rsl1122** [comment]
@mibby Sorry, yeah PluginBridge.jar is supposed to be in the PlanPluginBridge folder but I haven't been placing it there during development.

Here is a dev build of commit 8cf22de4b68477d7bbe0127c7b3872499c47d813
https://github.com/Rsl1122/Plan-PlayerAnalytics/releases/tag/3.5.0-DEV

**Comment by mibby** [comment]
@Rsl1122 Start-up time has slowed down _significantly_ with the new build.

```
**[04:34:31] [Server thread/INFO]: [Plan] Enabling Plan v3.5.0
[04:34:31] [Server thread/INFO]: [Plan] You're running the latest version
[04:34:31] [Server thread/INFO]: [Plan] Using locale: Default: EN
[04:34:31] [Server thread/INFO]: [Plan] Database init..
[04:34:31] [Server thread/INFO]: [Plan] Cleaning the database.
[04:34:31] [Server thread/INFO]: [Plan] Clean complete.
[04:34:31] [Server thread/INFO]: [Plan] mysql-database connection established.
[04:34:32] [Server thread/INFO]: [Plan] Initializing Webserver..
[04:34:32] [Server thread/INFO]: [Plan] Webserver running on PORT 8124
[04:34:32] [Server thread/INFO]: [Plan] Analysis | Boot analysis in 30 seconds..
[04:34:32] [Server thread/INFO]: [Plan] Player Analytics Enabled.
[04:34:41] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.0.4-SNAPSHOT-b
```

**Comment by mibby** [comment]
The web socket also seems to be quite laggier with hundreds of plotted data points charted on the activity display, as well as the scroll of the page being extremely long.

http://play.eoscraftmc.com:8124/bAkZj/server

**Comment by Rsl1122** [comment]
Opened #150 & #151
(In a month there are 2 629 744 seconds - If someone left/joined every 1000 seconds (~16,5minutes) It would still be 2629 points on the graph. I'll have to come up with some math for reducing points.)

**Comment by mibby** [comment]
How about a ticket for improved start-up time? 3.4.3 does not seem to have the issue, so perhaps it is caused by "queues now wait for each other"?

**Comment by Rsl1122** [comment]
It appears that it is an unrelated issue, or hidden (I don't know since debug was not enabled on the log you posted)
The plugin's onEnable method does nothing after "Player Analytics Enabled." is sent & from the timestamps it appears to run the whole method in 2 seconds.

Here what it tells me when I boot (SQLite with 14017 Players & All possible hooking plugins)
```
[18:40:25 INFO]: [Plan] Enabling Plan v3.5.0
[18:40:25 INFO]: [Plan] [DEBUG] -------------------------------------
[18:40:25 INFO]: [Plan] [DEBUG] Debug log: Plan v.3.5.0
[18:40:25 INFO]: [Plan] [DEBUG] Implements RslPlugin v.1.4.0
[18:40:25 INFO]: [Plan] [DEBUG] Bukkit Version: 1.12-R0.1-SNAPSHOT
[18:40:25 INFO]: [Plan] [DEBUG] Version: git-Spigot-7228328-d603539 (MC: 1.12)
[18:40:25 INFO]: [Plan] [DEBUG] -------------------------------------
[18:40:25 INFO]: [Plan] You're running the latest version
[18:40:25 INFO]: [Plan] [DEBUG] You're running the latest version
[18:40:25 INFO]: [Plan] Using locale: Default: EN
[18:40:25 INFO]: [Plan] [DEBUG] Using locale: Default: EN
[18:40:25 INFO]: [Plan] [DEBUG] Started task 70: DBConnectionPingTask MySQL, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 71: DBConnectionPingTask SQLite, Async.
[18:40:25 INFO]: [Plan] Database init..
[18:40:25 INFO]: [Plan] [DEBUG] Database init..
[18:40:25 INFO]: [Plan] [DEBUG] DB-SQLite: Init
[18:40:25 INFO]: [Plan] [DEBUG] Database Init sqlite
[18:40:25 INFO]: [Plan] [DEBUG] Database create tables
[18:40:25 INFO]: [Plan] [DEBUG] Database create tables took 2 ms
[18:40:25 INFO]: [Plan] [DEBUG] Started task 72: BukkitDataConversionTask, Async.
[18:40:25 INFO]: [Plan] Cleaning the database.
[18:40:25 INFO]: [Plan] [DEBUG] Cleaning the database.
[18:40:25 INFO]: [Plan] Clean complete.
[18:40:25 INFO]: [Plan] [DEBUG] Clean complete.
[18:40:25 INFO]: [Plan] [DEBUG] Database Init sqlite took 10 ms
[18:40:25 INFO]: [Plan] sqlite-database connection established.
[18:40:25 INFO]: [Plan] [DEBUG] sqlite-database connection established.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 73: ClearQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 74: SaveQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 75: SaveQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 76: GetQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 77: GetQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 78: ProcessQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 79: ProcessQueueConsumer, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Get CommandUse
[18:40:25 INFO]: [Plan] [DEBUG] Get CommandUse took 1 ms
[18:40:25 INFO]: [Plan] [DEBUG] Started task 80: PeriodicCacheSaveTask, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 81: TPSCountTimer, Sync.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 82: ReloadCacheUpdateTask, Async.
[18:40:25 INFO]: [Plan] Initializing Webserver..
[18:40:25 INFO]: [Plan] [DEBUG] Initializing Webserver..
[18:40:25 INFO]: [Plan] [DEBUG] Started task 83: WebServerTask, Async.
[18:40:25 INFO]: [Plan] Webserver running on PORT 8804
[18:40:25 INFO]: [Plan] [DEBUG] Webserver running on PORT 8804
[18:40:25 INFO]: [Plan] Analysis | Boot analysis in 30 seconds..
[18:40:25 INFO]: [Plan] [DEBUG] Analysis | Boot analysis in 30 seconds..
[18:40:25 INFO]: [Plan] [DEBUG] Started task 84: BootAnalysisTask, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Started task 85: PeriodicalAnalysisTask, Async.
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: AdvancedAchievements_achievements
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: AdvancedAchievements_achievementstable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Essentials_jailed
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Essentials_muted
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Essentials_warps
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Factions_faction
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Factions_power
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Factions_maxpower
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Factions_factionstable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: McMMO_inspectskilltable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: McMMO_analysistable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Jobs_inspecttable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Jobs_analysistable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: OnTime_votes
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: OnTime_votes_7d
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: OnTime_votes_30d
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: OnTime_refer
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: OnTime_refer_7d
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: OnTime_refer_30d
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Towny_townstable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Towny_town
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Vault_permgroup
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Vault_permgrouptable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Vault_balance
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: Vault_ecobalancetable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: ASkyBlock_islandname
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: ASkyBlock_islandresetsleft
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: ASkyBlock_island_count
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: GriefPrevention_claim_count
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: GriefPrevention_claim_area
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: GriefPrevention_claim_available
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: GriefPrevention_softmuted
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: GriefPrevention_inspectclaimtable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: SuperbVote_votes
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: SuperbVote_votetable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: ViaVersion_versiontable
[18:40:25 INFO]: [Plan] [DEBUG] Registered a new datasource: ViaVersion_version
[18:40:25 INFO]: [Plan] [DEBUG] Verboose debug messages are enabled.
[18:40:25 INFO]: [Plan] Player Analytics Enabled.
[18:40:25 INFO]: [Plan] [DEBUG] Player Analytics Enabled. // Within same second
[18:40:25 INFO]: [AntiVPN] Enabling AntiVPN v1.6
...
```

You can check with '/plan status timings' (After the server has been running for a while) if any particular thing has taken a really long time. - It does not currently cover everything though because everything is not benchmarked. If something appears out of the ordinary, please include the whole print of the command as some of the timings are part of a bigger process.

**Comment by mibby** [comment]
@Rsl1122 I use MySQL for the database. But I also do have quite a large Essentials player database, jobs database, and mcmmo user database. So perhaps it hangs when trying to read through thousands of files when initializing Player Analytics to check for who is jailed / banned?

Plan status timings.
http://paste.ubuntu.com/25021218/

ConcurrentModificationException.
http://paste.ubuntu.com/25021204/

**Comment by mibby** [comment]
Here is the debug log. It just freezes on ```Player Analytics Enabled```, doesn't state why. So could be an issue with MySQL database or scanning all the plugin compatibility features / files.

Debug.log
http://paste.ubuntu.com/25021712/

Start-up log with debug enabled.
http://paste.ubuntu.com/25021715/

Another NPE
http://paste.ubuntu.com/25021713/

**Comment by Rsl1122** [comment]
I'll try to add more benchmarks and debug messages to see if anything might cause an issue. It shouldn't be reading the other plugins data until analysis. 
Same with reading banned status - that is only read from bukkit files when player joins, otherwise it is taken from the database. (Didnt seem to take a long time to get the data from plan db)

**Comment by mibby** [comment]
Well then it could be an issue with mysql or the newly introduced "queues now wait for each other". :) Either way, it is significantly slower on mysql compared to 3.4.x.

**Comment by Rsl1122** [comment]
"Queues wait for each other" only affects processing (When event fires, it's info goes to processing queue, processing queue makes a get request - If a get request for that user is already in the get queue it doesn't make another one (What it previously did) but waits. 
Same deal with save queue if data is unprocessed in the processing queue.

**Comment by Rsl1122** [comment]
I have updated the debug release to the latest commit.

**Comment by mibby** [comment]
Doesn't seem to have fixed the hang or really explain why it hangs still.

Updated debug log.
http://paste.ubuntu.com/25027923/

Updated start-up log debug enabled.
http://paste.ubuntu.com/25027913/

I'll grab another status timings as it runs a bit longer throughout the day.

**Comment by mibby** [comment]
@Rsl1122 Also now getting a '404 Data was not found in cache' when trying to view the /server statistics page..

**Comment by mibby** [comment]
The vault number of members per group list is also incorrect. It states only 995 members when I actually have over 20,000 grouped members. Also guests aren't grouped in the permission file. Unless Plan keeps track of vault groups based on who logs in and writes it to the sql database?

**Comment by Rsl1122** [comment]
Sorry for not replying.
I'll start from the top.

Dunno what is causing that enable hang - I have not been able to reproduce it.
Reload breaks everything, it causes more SessionData instances to be added even when players don't leave - Tasks are not ended fast enough for the reload because things need to be saved so it will complain.

Players online graph is calculated using the start & end times of sessions & I have no idea how it managed to get into negative numbers - It'll most likely be rewritten to use the players online the TPS count task collects.

Formatting numbers on the graphs (Piecharts) has not been a priority because it requires writing another javascript function just for that.

Vault Permgroup table only includes players that are in the plan database because getOfflinePlayers method is way too slow & a "fake" OfflinePlayer object with Plan data is faster to use.
If you want all players you can /plan manage import offline - It takes a while to complete.

Branch merged because update is live.

**Comment by mibby** [comment]
@Rsl1122 I dropped all sql tables and disabled all listeners / plugin hooks. The start-up time is still tremendously slow using mysql so something definitely broke in-between 3.4 and 3.5. I'll create a ticket so hopefully it can be looked into or fixed in the code cleanup.

Using release build of Plan 3.5.0.

Start-up log.
http://paste.ubuntu.com/25053043/

Config
http://paste.ubuntu.com/25053050/

**Pull request merged**
