### PR TITLE
Some more modifications & bugfixes

### PR DESCRIPTION
**Pull request by Fuzzlemann**
Fixes a bug caused by my migration to forEach, further performance optimizations and so on, more details seen in the commit descriptions.

### CODE REVIEW

**Comment by Fuzzlemann** [comment]
The variables aren't necessary because if an error happens (e.g. NumberFormatException) the method just "resets" (whatever the right expression is), that's why the initialization at beginning is not necessary. 

I quote my IDE:
"This inspection points out the cases where a variable value is never used after its assignment, i.e.:  - the variable never gets read after assignment OR  - the value is always overwritten with another assignment before the next variable read OR  - the variable initializer is redundant (for one of the above two reasons)"

The messages... uhm... fail by me, it's updated by now.

For the && || readability, I'm not 100% sure too, but I think it just makes the code a little bit more "compact" and is imo more readable.
I'm personally using lombok for that kind of things, just because it's just too easy  to just place a @Data as annotation and auto-create getter, setter, hashcode, equals... methods, wow, I really sound like an advertisement, but if you're interested in deeper insight, here's the link to lombok: https://projectlombok.org/

**Comment by Rsl1122** [comment]
Alright I guess that's fine then

I would use lombok but my IDE (NetBeans) didn't support it (or the other way around).
Last time I tried to get into IntelliJ IDEA (it was because of Lombok last time too) I was completely lost without a project package/class list on the left side & open class tabs.

Comment something like "Done" so that I know when to merge this pr :)

**Comment by Fuzzlemann** [comment]
Lombok is compatible with Netbeans, see: https://projectlombok.org/setup/netbeans ^^
If you still want to migrate to IntelliJ, you can contact me, I will be glad helping you out :)

IntelliJ is a little bit hard to migrate, but if you completed the migration, it's really pushing the productivity and error searching, and it provides great JUnit5 integration!

PS: I did the exact same mistake, but now a little bit after a year of swapping to IntelliJ I know that you just pressed Alt + 1 :)

PSS: What do you think about an integration with bStats? http://bstats.org/

**Comment by Rsl1122** [comment]
I've been looking for metrics but gave up after I found that the old one had shut down. 
I'll look into bStats, thanks

**Comment by Fuzzlemann** [comment]
Another question: Do you know why the Format class in the FormatUtils isn't imported and I can't find a fitting import for it? (Isn't imported in the GitHub source too)

How my IDE sees it: http://i.imgur.com/TMjyGM3.png

**Comment by Rsl1122** [comment]
I don't know why it wouldn't be imported, it is a part of Abstract Plugin Framework. 
If the jar doesn't contain the class (the one in releases of that Repo) I forgot to press the build button before releasing. 

That config option sounds good. It would remove some data that is useless to some - The command table is limited to a length though, and the data points with typos are less likely to score higher use. 

Do you have a discord? It would be nice to chat with you.

**Comment by Fuzzlemann** [comment]
Yeah, I have discord. Just add me, my name is Fuzzlemann.

I take another look at the issue with the import.

**Comment by Fuzzlemann** [comment]
The new commit contains a geolocation cache.

One main advantage is, that the countries from 15.000 unique IPs can be retrieved.
This helps on big servers.
One second advantage is of course the performance side of things.

The not-so-important changes are listed in the commit description.

**Pull request merged**
